name: evansfrancisapp
description: Evans Francis App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dependency_plugin:
    path: dependency_plugin

  intl: ^0.18.0
  google_fonts: ^5.0.0
  dropdown_button2: ^2.1.4
  bot_toast: ^4.0.4
  url_launcher: ^6.1.11
  youtube: ^1.0.1 # for getting thumbnail
  flutter_screenutil: ^5.8.4
  flex_color_scheme: ^7.1.2

  #Local
  flutter_inappwebview: ^5.7.2+3
  carousel_slider: ^4.2.1
  flutter_quill: ^7.2.11
  pinput: ^2.2.31
  country_picker: ^2.0.20
  firebase_cached_image: ^0.4.4
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.2

dependency_overrides:
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

#  assets:
#    - assets/images/
#    - assets/menu_images/
